; >>> Challenge 2
; Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
; By starting with 1 and 2, the first 10 terms will be:

; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; By considering the terms in the Fibonacci sequence whose values do not exceed four million,
; find the sum of the even-valued terms.

section .data

    msg db "Hello World!",0xa


section .text
 
    global _start
    extern _printNumber
    extern _writeString

_start:

    mov rax, 1
    mov rbx, 1
    mov rcx, 2
    repeat:
        ; Prints up to values not exceeding 4,000,000
        cmp rax, 32
        je repeat_fin

        ; Adds then swaps
        add rbx, rcx
        xchg rbx, rcx

        ; Prints out each value of the sequence
        push rax
        mov rax, rbx
        call _printNumber
        pop rax
        
        inc rax
        jmp repeat

    repeat_fin:
    


    ; exit()
    mov rbx, 0
    mov rax, 1
    int 80h